services:
  - type: web
    name: sms-receiver
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi --log-file -"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: sms-receiver-db
          property: connectionString

databases:
  - name: sms-receiver-db
    databaseName: sms_receiver
    plan: free
